Organization detail
diyojen-io/tech-talks-hub pull request #11
Opened 2024-06-07 11:25 UTC by ozknaksoy

2024-06-07 14:22 UTC, ucemrecan commented on src/app/components/Hero.js
> +  alignItems: "start",
"flex-start" ya da silebilirsin default'u böyle çalışıyor olmalı.

2024-06-07 14:23 UTC, ucemrecan commented on src/app/layout.js
> +// export const metadata = {
Console log'ları silelim.

2024-06-12 12:44 UTC, ucemrecan commented on src/app/organization/[organization-detail]/page.js
> +        <Stack>
Stack silebilirsin, burada calismaz gibi

2024-06-12 12:47 UTC, ucemrecan requested changes
Guzel olmus eline saglik, bir kac duzeltme yazdim onlari yaptiktan sonra tamamdir.

2024-06-14 08:24 UTC, ozknaksoy commented on src/app/components/Hero.js
> +  alignItems: "start",
Hero.js kaldirildi

2024-06-14 08:38 UTC, ozknaksoy commented on src/app/layout.js
> +// export const metadata = {
kaldirildi

2024-06-14 08:52 UTC, ozknaksoy commented on src/app/organization/[organization-detail]/page.js
> +          <Button sx={{ marginRight: "10px" }} variant="contained">
follow ve join butonu icona cevrildi.

2024-06-25 08:32 UTC, merged