Login
diyojen-io/tech-talks-hub pull request #12
Opened 2024-06-07 13:56 UTC by ozknaksoy

login sayfasinin Ui olarak belli bolumleri tamamlandi.

2024-06-12 12:21 UTC, ucemrecan commented on src/app/components/Navbar.js
> +              <>
fragment yerine stack icine alalim, spacing'i oradan verelim. marginRight'lara gerek kalmaz.

2024-06-12 12:22 UTC, ucemrecan commented on src/app/components/Navbar.js
> +          <Stack direction="row" pt={2} pb={2}>
stack'ler iki kosul icinde iceride olsun, bu sekilde calismaz

2024-06-12 12:22 UTC, ucemrecan commented on src/app/components/Navbar.js
> +                <NextLink href="/signUp" passHref>
path'ler /sign-up seklinde olmali

2024-06-12 12:24 UTC, ucemrecan commented on src/app/layout.js
> +              <AuthProvider>
auth provider, hiyearsi olarak en yukardan sarmali

2024-06-12 12:26 UTC, ucemrecan commented on src/app/organization/[organization-detail]/page.js
>          <Stack>
Stack muhtemelen burada calismiyor ve ihtiyac yok

2024-06-12 12:28 UTC, ucemrecan commented on src/app/organization/[organization-detail]/page.js
> +                <Box>
bu box fazla gibi burada

2024-06-12 12:40 UTC, ucemrecan commented on src/app/organization/new/page.js
> +                    <input
Simdilik bu sekilde kalabilir. Burayi mui avatar ve react-dropzone kullanarak daha duzgun hale getirmeliyiz. Bunun issue'larini acacagim.

2024-06-12 12:42 UTC, ucemrecan requested changes
Bir kac duzeltilecek yer var onlar bittiginde okey.

2024-06-14 09:06 UTC, ozknaksoy commented on src/app/components/Navbar.js
> +              <>
duzenlendi

2024-06-14 09:07 UTC, ozknaksoy commented on src/app/components/Navbar.js
> +          <Stack direction="row" pt={2} pb={2}>
daha detayli aciklar misin?

2024-06-14 09:09 UTC, ozknaksoy commented on src/app/components/Navbar.js
> +                <NextLink href="/signUp" passHref>
duzenledi.

2024-06-14 09:22 UTC, ozknaksoy commented on src/app/components/TechTalk.js
> +  const [value, setValue] = React.useState("one");
duzenlendi

2024-06-14 09:22 UTC, ozknaksoy commented on src/app/layout.js
> +              <AuthProvider>
en yukari alindi.

2024-06-14 14:02 UTC, ozknaksoy commented on src/app/components/Navbar.js
> +          <Stack direction="row" pt={2} pb={2}>
burda disaridaki padding veren stack'i WrapperBox'a tasidim, condition icinde her iki durum icin ayri ayri Stack icerisine aldim

2024-06-20 12:26 UTC, ozknaksoy commented on src/app/organization/new/page.js
> +                    <input
mui avatar ve react-dropzone ile tekrar duzenledim

2024-06-20 16:39 UTC, ucemrecan commented on src/app/components/TechTalk.js
>            <Box>
Öncelikle box içinde box olmaz demedim. Buradaki gibi kullanırsan gereksiz kullanmış olursun demek istedim. Dikkatli incelersen buradaki box bütün elementleri kapsıyor, üstünde style vererek bir box daha tanımlamışsın. Tek bir box ile de çözersin burayı.

2024-06-20 16:41 UTC, ucemrecan commented on src/app/components/TechTalk.js
> +                <NextLink
Avatar'a tıklandığında da yönlendir.

2024-06-20 16:42 UTC, ucemrecan commented on src/app/components/TechTalk.js
> +  marginTop: "20px",
Neye göre padding neye göre margin veriyorsun? burada tek satırda `margin: 20px 0` versen olmaz mı?

2024-06-20 16:43 UTC, ucemrecan commented on src/app/layout.js
>  // export const metadata = {
commentleri uçur.

2024-06-20 17:02 UTC, ucemrecan commented on src/app/login/page.js
> +  marginTop: theme.spacing(8),
Bu şekilde olmaz, login ve create organization'ı sayfanın ortasına yerleştirmeliyiz. Bunun içinde öncelikle layout'a ayar çekerek yapabilirsin. main'in minHeight'i 100vh - navbar olmalı. Daha sonra login ve create organization flex yetenekleri ile ortalanmalı. Bu şekilde marginle olmaz.

2024-06-20 17:03 UTC, ucemrecan commented on src/app/login/page.js
> +        initialValues={{ email: "", password: "" }}
Bunlara Validation lazım. yup kullanabilirsin.

2024-06-20 17:04 UTC, ucemrecan commented on src/app/main/layout.js
> +      <Container sx={{ paddingTop: 3 }} maxWidth="md">
paddingTop'ı kaldıralım. main'in minHeight'i dene.

2024-06-20 17:06 UTC, ucemrecan commented on src/app/organization/[organization-detail]/page.js
> +                <Box>
Bunun benzeri bir konuda yorum yaptım.

2024-06-20 17:09 UTC, ucemrecan commented on src/app/organization/new/page.js
> +const Dropzone = ({ onDrop }) => {
Logo yüklemeye ait bütün işler (logo yüklendiğinde gösterilmesi dahil) ayrı component'te olsun. AvatarUpload gibi bir isimlendirme yapabilirsin.

2024-06-20 17:10 UTC, ucemrecan commented on src/app/organization/new/page.js
> +                  {() => (
Burayı neden böyle yazdın?

2024-06-20 17:11 UTC, ucemrecan requested changes
Düzeltilecek yerler var.

2024-06-21 09:22 UTC, ozknaksoy commented on src/app/components/TechTalk.js
> +                <NextLink
NextLink ile Avatar ve Typography'i sardım.

2024-06-21 09:27 UTC, ozknaksoy commented on src/app/components/TechTalk.js
> +  marginTop: "20px",
duzenlendi.

2024-06-21 09:27 UTC, ozknaksoy commented on src/app/layout.js
>  // export const metadata = {
uçurdum hocam.

2024-06-21 09:36 UTC, ozknaksoy commented on src/app/components/TechTalk.js
>            <Box>
Box'i sildim ve bir ustundeki BoxStyle'in css ozelliklerini guncelledim.

2024-06-21 10:29 UTC, ozknaksoy commented on src/app/login/page.js
> +  marginTop: theme.spacing(8),
FormContainer'a   minHeight: `calc(100vh - 56px)`, vererek duzelttik.

2024-06-21 10:30 UTC, ozknaksoy commented on src/app/main/layout.js
> +      <Container sx={{ paddingTop: 3 }} maxWidth="md">
duzenlendi.

2024-06-21 11:20 UTC, ozknaksoy commented on src/app/organization/new/page.js
> +                  {() => (
anlamadim soruyu daha detayli sorar misin ?

2024-06-21 14:16 UTC, ozknaksoy commented on src/app/organization/new/page.js
> +const Dropzone = ({ onDrop }) => {
AvatarUpload.js adinda  ayri bir component olarak ekledim ama yanlis yapmis olabilirim.

2024-06-25 08:30 UTC, merged