Tech Talk detail page has been edited.
diyojen-io/tech-talks-hub pull request #13
Opened 2024-06-14 08:23 UTC by ozknaksoy

2024-06-17 20:53 UTC, ucemrecan commented on src/app/tech-talks/[techtalk]/page.js
> +          <CommentSection>
Buralarda scope gereksiz uzamış yani tech-detail sayfası oluşturmuşsun ama kodun büyük bölümü comment ile alakalı işlerle dolmuş. Comment bölümlerini ayrı component olarak yapıp buraya ekleyebilirsin.

2024-06-17 20:57 UTC, ucemrecan commented on src/app/tech-talks/[techtalk]/page.js
> +          <Container sx={{ display: "flex", justifyContent: "flex-end" }}>
Burada Container olmaz, style'leri üstteki box'a verebilirsin. Burada container'in hangi özelliğinden yararlandın? Sadece iconlar için container kullanmışsın, container genel olarak en dışta kullanılan bir layout.

2024-06-17 20:58 UTC, ucemrecan commented on src/app/tech-talks/[techtalk]/page.js
>      <Container sx={{ width: "100%" }}>
Bu witdh muhtemelen çalışmıyor.

2024-06-17 21:01 UTC, ucemrecan commented on src/app/tech-talks/[techtalk]/page.js
>        <Head>
Head, metadata ve SEO için kullanılıyor. Container'in üstünde en dışarıda olmalı, sayfada görebileceğin bir şey değil. Developer tool'da head tagları içinde görebilirsin.

2024-06-17 21:04 UTC, ucemrecan requested changes
Genel olarak pr'larında çalışmayan style'lar fazla sayıda oluyor, push'lamadan önce bunları azaltmaya çalışalım.

2024-06-19 08:52 UTC, ozknaksoy commented on src/app/tech-talks/[techtalk]/page.js
> +          <Container sx={{ display: "flex", justifyContent: "flex-end" }}>
Box icinde box yapmamak adina container kullanmistim.  TechTalkBox butun layout'u kapsiyor.  container'in style'lari uzte alirsam iconlari kendi basina sağa yaslayamiyorum.

2024-06-19 08:53 UTC, ozknaksoy commented on src/app/tech-talks/[techtalk]/page.js
>      <Container sx={{ width: "100%" }}>
duzeltildi.

2024-06-19 08:58 UTC, ozknaksoy commented on src/app/tech-talks/[techtalk]/page.js
>        <Head>
fragment'a sarildi ve duzeltildi.

2024-06-19 20:27 UTC, ozknaksoy commented on src/app/tech-talks/[techtalk]/page.js
> +          <CommentSection>
component altinda Comment.js adinda ayri bir component olarak eklendi

2024-06-20 09:53 UTC, eenesunal commented on src/app/hooks/useLocalStorage.js
>    });
`const [value, setValue] = useState(() => {
  if (typeof window !== "undefined") {
    const storedValue = window.localStorage.getItem(key);
    return storedValue !== null ? JSON.parse(storedValue) : defaultValue;
  } else {
    return defaultValue;
  }
});`

2024-06-20 16:08 UTC, merged