Feature/tth 9
diyojen-io/tech-talks-hub pull request #22
Opened 2024-12-12 20:41 UTC by alperendnc

1. **Profile Page UI**: The UI for the profile page has been created.
2. **User Information Fields**: Fields have been added to allow the user to update information such as name, email, etc.
3. **Profile Picture Upload**: An area has been created where the user can upload their profile picture.

2024-12-13 17:43 UTC, ucemrecan requested changes
slack üzerinden review yapıldı.

2024-12-23 10:30 UTC, ucemrecan commented on src/sections/profile/ProfilePasswordForm.tsx
> +      console.log('Password Change Values: ', values);
- console log silelim. 
- parola update nerede ediliyor? Firebase metod'u kullanilmamis

2024-12-23 10:31 UTC, ucemrecan commented on src/sections/profile/ProfilePasswordForm.tsx
> +              {[
Listeleri boyle direkt map'lemeyelim. Constant olarak import altinda yukarida bir yere yazabilirsin. const requirements = [...] gibi

2024-12-23 10:32 UTC, ucemrecan commented on src/sections/profile/ProfilePasswordForm.tsx
> +                  {item.met ? <CheckCircleIcon color="success" /> : <CancelIcon color="error" />}
met yerine daha anlamli bir sey yazalim

2024-12-23 10:32 UTC, ucemrecan commented on src/app/icons/index.tsx
icons tarzi seyleri public/assets gibi bir yerde tutman daha dogru olur. app icinde kesinlikle tutmuyoruz

2024-12-23 10:32 UTC, ucemrecan requested changes
review yapildi.

2024-12-23 15:40 UTC, alperendnc commented on src/sections/profile/ProfilePasswordForm.tsx
> +      console.log('Password Change Values: ', values);
henuz edilmiyo abi baslangicini yaptim sadece

2024-12-24 02:04 UTC, alperendnc commented on src/sections/profile/ProfilePasswordForm.tsx
> +              {[
map'lemezsek hepsini manuel olarak mi yazacagim abi

2024-12-24 03:10 UTC, alperendnc commented on src/sections/profile/ProfilePasswordForm.tsx
> +                  {item.met ? <CheckCircleIcon color="success" /> : <CancelIcon color="error" />}
requirementMet nasil abi

2024-12-27 12:59 UTC, ucemrecan commented on src/app/components/FormCard/FormCard.scss
app icinde router dosyalar disinda baska bir sey olmamali. bu component kullaniliyorsa app'in disinda (ayni hiyearside) bulunan component'in icine koyabilirsin yoksa silelim.

2024-12-27 13:13 UTC, ucemrecan commented on public/assets/icons/index.tsx
Bu olay baya gereksiz import edip export edecegine kullandigin yerde tek seferde import et kullan, niye boyle yaptin ki?

2024-12-27 13:14 UTC, ucemrecan commented on src/context/AuthContext.tsx
> +    if (!user) {
bunu client'ta senin yapman gerek, kullanici authenticate degilse nasil change password s ekmesine gelebiliyor? Hatta profile settings'e girebiliyor?

2024-12-27 13:15 UTC, ucemrecan commented on src/context/AuthContext.tsx
> +      await reauthenticateWithCredential(user, credential);
buna gerek var mi?

2024-12-27 13:16 UTC, ucemrecan commented on src/context/AuthContext.tsx
> +     catch (error: any) {
error yakaladiginda hicbir sey yapmiyor

2024-12-27 13:16 UTC, ucemrecan commented on src/context/AuthContext.tsx
> +        update,
updateProfile gibi daha explicit isim verelim. hem update hem updatePassword var kafa karistirici

2024-12-27 13:17 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +import {
yukarida export etmenin hicbir mantigi yok, burada direkt mui/icons'tan import edebilirsin

2024-12-27 13:17 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +const InputField = ({ name, label, icon }) => (
bunlari components'e tasiyalim

2024-12-27 13:17 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +const SocialInputField = ({ name, label, icon }) => (
bunlari components'e tasiyalim

2024-12-27 13:17 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +const SocialInputField = ({ name, label, icon }) => (
Ve parametrelerin type'larini belirtelim

2024-12-27 13:17 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +const InputField = ({ name, label, icon }) => (
Ve parametrelerin type'larini belirtelim

2024-12-27 13:19 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +  useEffect(() => {
simdi buraya gelen kullanici zaten var oldugu icin bazi field'lari dolu olmali. ornegin email gibi. bunu useEffect'e yapmanin bi mantigi yok. yukarida defaultvalues'a tanimlaman daha dogru

2024-12-27 13:19 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +      console.log('values: ', values);
console silelim

2024-12-27 13:20 UTC, ucemrecan commented on src/sections/profile/ProfileBasicInformationForm.tsx
> +          <Button type="submit" disabled={isSubmitting}>
LoadingButton olarak kullansan daha iyi olur. mui/labs gibi bir pakette var

2024-12-27 13:21 UTC, ucemrecan commented on src/sections/profile/ProfilePasswordForm.tsx
> +import {
mui icons'dan direkt import edelim

2024-12-27 13:22 UTC, alperendnc commented on public/assets/icons/index.tsx
ilk basda oyle yapmistim abi sonra proje icinde farkli yerlerde icon kullaniyoruz diye bir dosyaya tasidimi sonra da halihazirda bi icons dosyasi oldugunu gordum oraya tasidim ben de hepsini

2024-12-27 13:22 UTC, ucemrecan requested changes
Degisiklikler comment olarak yazildi

2024-12-27 13:28 UTC, alperendnc commented on src/context/AuthContext.tsx
> +    if (!user) {
bunu ben de fark ettim abi soyle bir sey de oluyor  kullanici sifre degistirip log out oldukdan sonra da bu sayfada kalabiiyor

2024-12-27 13:30 UTC, alperendnc commented on src/context/AuthContext.tsx
> +      await reauthenticateWithCredential(user, credential);
sifre degistirmek icin once mevcit sifreyi dogruluyoruz burda abi

2024-12-27 13:31 UTC, ucemrecan commented on src/context/AuthContext.tsx
> +    if (!user) {
ayni seyden bahsediyoruz, cozumu burasi degil sonuc olarak. Authenticate degilse kullanici profile settings'i gormemeli

2024-12-27 13:36 UTC, ucemrecan commented on src/context/AuthContext.tsx
> +      await reauthenticateWithCredential(user, credential);
Bu yeniden oturum acmak icin kullaniliyor. Kullanici zaten authenticate oldugu icin bu sayfaya gelmeyecek mi, mantikli geliyor mu?

2024-12-30 20:16 UTC, ucemrecan commented on src/context/AuthContext.tsx
> +    await signInWithEmailAndPassword(AUTH, user.email, currentPassword);
Sign in olmamasi lazim zaten authenticate olmus olmali

2024-12-30 20:17 UTC, ucemrecan requested changes
firebase context'te sikintilar var

2025-01-21 10:17 UTC, merged