Role guard
diyojen-io/tech-talks-hub pull request #22
Opened 2024-07-01 14:14 UTC by ozknaksoy

2024-07-03 08:01 UTC, ucemrecan commented on src/app/contexts/AuthContext.js
> +    dispatch({ type: "LOGIN", payload: data.email });
axios ile istek atilmamis,  bu sekilde mock adapter calismaz

2024-07-03 08:02 UTC, ucemrecan commented on src/app/login/page.js
> +          console.log("values: ", values);
console'u silelim. try catch'e alalim burayi cunku hata donerse burasi patlar

2024-07-03 08:03 UTC, ucemrecan commented on src/app/sign-up/page.js
> +      console.log("Form Values: ", values);
console silelim, sign up icin de loginde oldugu gibi context'te fonksiyon yazilmasi lazim

2024-07-03 08:03 UTC, ucemrecan commented on src/app/tech-talks/page.js
> +  console.log("user: ", user);
console.log'lari silelim

2024-07-03 08:05 UTC, ucemrecan commented on src/app/utils/axios.js
> +mock.onGet("/users").reply((config) => {
bu suan hicbir ise yaramiyor, login icin yapman gerek

2024-07-03 08:06 UTC, ucemrecan requested changes
Bu kısmın ofiste tekrar üzerinden geçelim, ondan sonra düzeltmeleri yaparsın

2024-07-08 08:23 UTC, ozknaksoy commented on src/app/sign-up/page.js
> +      console.log("Form Values: ", values);
role guard branchinde sign-up dosyasi yok burayi develop branchinden duzeltecegim.

2024-07-08 10:33 UTC, ucemrecan approved these changes

2024-07-08 10:35 UTC, merged